# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy Client to GitHub Pages

on:
  push:
    branches:
      - master
    paths:
      - src/client/**
  workflow_dispatch:
    
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.2 ## replace by latest version without it you will see Expected format {org}/{repo}[/path]@ref. Actual 'AhsanAyaz/angular-deploy-gh-pages-actions',Input string was not in a correct format.
        with:
          github_access_token: ${{ secrets.ACCESS_TOKEN }} # see the Configuration section for how you can create secrets
          build_configuration: production # The build environment for the app. please look configurations in your angular.json
          base_href: /WebRTCVideoCallAssistant/
          deploy_branch: gh-pages 
          angular_dist_build_folder: dist/web-rtcvideo-call-assistant.client
